targetInputDevices:
  - HX Stomp
  - SINCO
targetOutputDevice:
  - ZOOM MS Series
targetOutputDeviceChannel: 3
changeControlMaps:
  -
    ccNum: 0
    action: 'tunerOnOff'
  -
    ccNum: 1
    action: 'effectOnOff'
    effectPosition: 0x01
  -
    ccNum: 2
    action: 'changeEffectParam'
    effectPosition: 0x01
    paramNum: 0x02
  -
    ccNum: 3
    action: 'changeEffectParam'
    effectPosition: 0x01
    paramNum: 0x04